# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Solving Partial Differential Equations - MOOC
author: B. Knaepen & Y. Velizhanina
logo: logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints",
                  solving_pde_mooc/notebooks/drawings, 
                  solving_pde_mooc/notebooks/figures, 
                  solving_pde_mooc/notebooks/modules, 
                  solving_pde_mooc/notebooks/styles,
                  solving_pde_mooc/notebooks/demos, 
                  solving_pde_mooc/README.md,
                  README.md, logo.png]
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 300

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - colon_fence
    - amsmath
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

bibtex_bibfiles:
    - references.bib

sphinx:
  config:
    bibtex_reference_style: unsrt

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    numfig_secnum_depth: 0

# Information about where the book exists on the web
repository:
  url: https://github.com/aquaULB/solving_pde_mooc  # The URL to your book's repository
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : false  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : "" # The URL of Google Colab (https://colab.research.google.com)